version: "3.8"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
